# apiVersion: v1
# kind: Service
# metadata:
#   name: vpromq01
# spec:
#   ports:
#   - port: 5672
#     targetPort: vpromq01-port
#     protocol: TCP
#   selector:
#     app: vpromq01
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
    protocol: TCP
  - name: http
    port: 15672          # âœ… Add management UI port
    targetPort: http
    protocol: TCP
  selector:
    app: vpromq01
  type: ClusterIP
