name: java-maven-eks-app.gitops-actions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: vprofile-eks
  ECR_REPOSITORY: vproapp-gitops-learning

jobs:
  Testing:
   runs-on: ubuntu-latest
  steps:
      - name: Code checkout
        uses: actions/checkout@v4
  
      - name: Maven test
        run: mvn test 
  
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup java 11 to be default ( sonar-scanner requirment as of 5.x)
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      # Setup sonar-scanner
      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} 
          -Dsonar.source=src/
          -Dsonar.junit.reportsPath=target/surefile-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      # Check the quality gate status
      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail the steps after specific time
        timeout-minutes: 5
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}

      

        